include ../Makefile.inc

all: cfgmgr.o cuvector.o timer.o tausgen.o

cfgmgr.o : cfgmgr.hxx cfgmgr.cpp

cuvector.o : cuvector.hxx cuvector.cpp

timer.o : timer.hxx timer.cpp

tausgen.o : tausgen.hxx tausgen.cpp

clean:
	rm -rf cfgmgr.o cuvector.o timer.o
